### ISSUE TITLE
Use data class

### ISSUE THREAD

**Issue by solemn-leader** [leffff/stackboost#6]
https://docs.python.org/3/library/dataclasses.html

https://github.com/leffff/stackboost/blob/0f42f861fef244156e39a6177b9bd9f2eaa0be82/stackboost/core.py#L18
https://github.com/leffff/stackboost/blob/0f42f861fef244156e39a6177b9bd9f2eaa0be82/stackboost/core.py#L61

**Comment by leffff** [comment]
Dataclasses added
